---

- name: copy nomad-bootstrap script
  ansible.builtin.copy:
    src: nomad-bootstrap
    dest: /opt/nomad/bin/nomad-bootstrap
    mode: 0750
    owner: nomad
    group: nomad
  tags:
    - nomad-bootstrap

- name: create nomad-bootstrap service
  ansible.builtin.template: src=templates/nomad-bootstrap.service.j2 dest=/usr/lib/systemd/system/nomad-bootstrap.service owner=root group=root mode=0644
  notify:
    - nomad daemon-reload

- name: create directory for systemd drop-ins
  ansible.builtin.file:
    path: /etc/systemd/system/nomad-bootstrap.service.d
    state: directory
    mode: 0755
