---

- name: set br_netfilter module configuration
  ansible.builtin.copy:
    content: "br_netfilter"
    dest: "/etc/modules-load.d/br_netfilter.conf"
    mode: 0644
    owner: root
    group: root
  tags:
    - ferm-conf
  when: not nomad_role_debug | bool

- name: enable systemd-modules-load.service
  ansible.builtin.service:
    name: systemd-modules-load
    enabled: true
  tags:
    - ferm-conf
  when: not nomad_role_debug | bool

- name: add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present
  tags:
    - ferm-conf
  when: not nomad_role_debug | bool

- name: set recommended kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ nomad_client_tunables }}"
  tags:
    - ferm-conf
  when: not nomad_role_debug | bool

- name: include escapace.cni role
  ansible.builtin.include_role:
    name: escapace.cni

- name: copy run-nomad-network script
  ansible.builtin.copy:
    src: files/run-nomad-network
    dest: "{{ nomad_bin_dir }}/run-nomad-network"
    mode: 0755
    owner: root
    group: root
  tags:
    - run-nomad-network
