---

- name: nomad group
  ansible.builtin.group:
    name: nomad
    state: present
    system: true

- name: nomad user
  ansible.builtin.user:
    name: nomad
    group: nomad
    system: true
    create_home: false

- name: packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nomad_packages }}"

- name: create nomad directories
  file:
    owner: nomad
    group: nomad
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ nomad_dir }}"
    - "{{ nomad_bin_dir }}"

- name: create nomad directories
  file:
    owner: nomad
    group: nomad
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "{{ nomad_dir }}/data"
    - "{{ nomad_dir }}/config"
    - "{{ nomad_dir }}/tls"
    - "{{ nomad_dir }}/tls/ca"
    - "{{ nomad_dir }}/plugins"

- name: download nomad
  get_url:
    url: "{{ nomad_zip_url }}"
    dest: "/tmp/{{ nomad_pkg }}"
    checksum: "sha256:{{ nomad_checksum_file_url }}"
  changed_when: false

- name: extract nomad
  ansible.builtin.unarchive:
    src: "/tmp/{{ nomad_pkg }}"
    dest: "{{ nomad_bin_dir }}"
    remote_src: true
  changed_when: false

- name: chcon nomad binary
  ansible.builtin.file:
    path: "{{ nomad_bin_dir }}/nomad"
    owner: nomad
    group: nomad
    mode: 0755
    setype: bin_t
    seuser: system_u

- name: create a nomad symbolic link
  ansible.builtin.file:
    src: "{{ nomad_bin_dir }}/nomad"
    dest: /usr/bin/nomad
    owner: nomad
    group: nomad
    mode: 0755
    state: link

- name: copy run-nomad script
  ansible.builtin.copy:
    src: files/run-nomad
    dest: "{{ nomad_bin_dir }}/run-nomad"
    mode: 0770
    owner: nomad
    group: nomad
  tags:
    - run-nomad

- name: create directory for systemd drop-ins
  file:
    path: /etc/systemd/system/nomad.service.d
    owner: root
    group: root
    state: directory
    mode: 0755

- name: cleanup
  file:
    path: "/tmp/{{ nomad_pkg }}"
    state: "absent"
  changed_when: false

- include_tasks: storage-setup.yml
  when: (storage_setup_physical_device is defined) and (storage_setup_physical_device | length > 0) and (nomad_volume|bool)

- include_tasks: nomad-client.yml
  when: nomad_server | bool is false
  tags:
    - nomad-network
    - ferm-conf
