---

- name: copy nomad-bootstrap script
  ansible.builtin.copy:
    src: nomad-bootstrap
    dest: /opt/nomad/bin/nomad-bootstrap
    mode: 0750
    owner: nomad
    group: nomad
  tags:
    - nomad-bootstrap

- name: create nomad-bootstrap service
  ansible.builtin.template:
    src: templates/nomad-bootstrap.service.j2
    dest: /usr/lib/systemd/system/nomad-bootstrap.service
    owner: root
    group: root
    mode: 0644
  notify:
    - nomad daemon-reload

- name: create directory for systemd drop-ins
  ansible.builtin.file:
    path: /etc/systemd/system/nomad-bootstrap.service.d
    state: directory
    mode: 0755

- name: copy nomad-snapshot script
  ansible.builtin.copy:
    src: nomad-snapshot
    dest: /opt/nomad/bin/nomad-snapshot
    mode: 0750
    owner: nomad
    group: nomad
  tags:
    - nomad-snapshot

- name: create nomad-snapshot service
  ansible.builtin.template:
    src: templates/nomad-snapshot.service.j2
    dest: /usr/lib/systemd/system/nomad-snapshot.service
    owner: root
    group: root
    mode: 0644
  notify:
    - nomad daemon-reload

- name: create directory for systemd drop-ins
  ansible.builtin.file:
    path: /etc/systemd/system/nomad-snapshot.service.d
    state: directory
    mode: 0755
