#!/usr/bin/env bash

set -e
set -u
set -o pipefail

readonly NOMAD_MIN_PEERS="2"

readonly NOMAD_CA_FILE="/opt/nomad/tls/ca/nomad-ca.pem"
NOMAD_CERT_FILE=
NOMAD_KEY_FILE=

if [[ -f "/opt/nomad/tls/nomad-server.pem" ]]; then
  NOMAD_CERT_FILE="/opt/nomad/tls/nomad-server.pem"
else
  NOMAD_CERT_FILE="/opt/nomad/tls/nomad-client.pem"
fi

if [[ -f "/opt/nomad/tls/nomad-server-key.pem" ]]; then
  NOMAD_KEY_FILE="/opt/nomad/tls/nomad-server-key.pem"
else
  NOMAD_KEY_FILE="/opt/nomad/tls/nomad-client-key.pem"
fi

function api() {
  curl -s -k -f \
    –cacert "${NOMAD_CA_FILE}" \
    –cert "${NOMAD_CERT_FILE}" \
    –key "${NOMAD_KEY_FILE}" \
    "https://[::1]:4646${1}"
}

function nomad_check_peers() {
  if [[ "$(api "/v1/status/peers" | jq -r '.|length' 2>/dev/null)" -ge "${NOMAD_MIN_PEERS}" ]]; then
    true
  else
    return 1
  fi
}

function nomad_online() {
  nomad_check_peers
}

nomad_online
