#!/bin/bash
# This script is used to configure and run Nomad on an AWS server.

set -e
set -u
set -o pipefail

umask 027

SCRIPT_DIR=
SCRIPT_NAME=
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="$(basename "$0")"

readonly NOMAD_CONFIG_FILE="default.hcl"
readonly SYSTEMD_CONFIG_PATH="/usr/lib/systemd/system/nomad.service"
readonly NOMAD_BOOTSTRAP_SYSTEMD_CONFIG_PATH="/etc/systemd/system/nomad-bootstrap.service.d/010-environment.conf"
readonly AWS_ASG_TAG_KEY="aws:autoscaling:groupName"
readonly MAX_RETRIES=30
readonly SLEEP_BETWEEN_RETRIES_SEC=10

function wrap() {
  local strings="${1}"

  local length
  local cols
  local width

  length="$(echo -n "${strings}" | awk -F '|' '{print $1}' | awk '{ print length }' | sort -n | tail -1)"
  cols="$(tput cols)"

  if [[ $(((cols - 4) / length)) -ge 2 ]]; then
    if [[ $((cols - length - 4)) -ge 80 ]]; then
      width=80
    else
      width=$((cols - length - 4))
    fi

    echo -e "${strings}" |
      fold -s -w "${width}" |
      sed -e "/--/! s|^| \||g" |
      column -t -s '|' |
      sed 's/^/  /'
  else
    local lines
    local line
    readarray -t lines <<<"${strings}"
    local option
    local description

    if [[ "${cols}" -ge 80 ]]; then
      width="78"
    else
      width=$((cols - 2))
    fi

    for line in "${lines[@]}"; do
      option="${line%%|*}"
      description=${line#*|}

      echo "${option}"
      echo
      echo "${description}" | fold -s -w "${width}" | sed 's/^/  /'
      echo
    done
  fi
}

function print_usage() {
  echo
  echo "Usage: $SCRIPT_NAME [OPTIONS]"
  echo
  echo "This script is used to configure and run Nomad on an AWS server."
  echo
  echo "Options:"
  echo

  wrap "$(
    echo -e "--role|The instance role, one of \"server\", \"client\" or \"bastion\"."
    echo -e "--environment|A single environment variable in the key/value pair form 'KEY=\"val\"' to pass to Nomad as environment variable when starting it up."
    echo -e "--secrets-bucket-name|AWS S3 secrets bucket name."
    echo -e "--verify-server-hostname|When passed in, enable server hostname verification as part of RPC encryption."
    echo -e "--interface|Bind to interface."
    echo -e "--ipv6|Use IPv6."
  )"
  echo
}

function log() {
  local -r level="$1"
  local -r message="$2"
  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  echo >&2 -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
}

function log_info() {
  local -r message="$1"
  log "INFO" "$message"
}

function log_warn() {
  local -r message="$1"
  log "WARN" "$message"
}

function log_error() {
  local -r message="$1"
  log "ERROR" "$message"
}

# Based on code from: http://stackoverflow.com/a/16623897/483528
function strip_prefix() {
  local -r str="$1"
  local -r prefix="$2"
  echo "${str#$prefix}"
}

function assert_not_empty() {
  local -r arg_name="$1"
  local -r arg_value="$2"

  if [[ -z "$arg_value" ]]; then
    log_error "The value for '$arg_name' cannot be empty"
    print_usage
    exit 1
  fi
}

function split_by_lines() {
  local prefix="$1"
  shift

  for var in "$@"; do
    echo "${prefix}${var}"
  done
}

function get_object() {
  local -r secrets_bucket_name="$1"
  local -r source="$2"
  local -r target="$3"
  local -r user="$4"

  local -r key="${EC2_INSTANCE_REGION}/${source}"

  log_info "Downloading ${key}"

  aws s3api get-object \
    --bucket "${secrets_bucket_name}" \
    --key "${key}" \
    "${target}" >/dev/null || exit 1

  chown "${user}:${user}" "${target}"
}

function get_object_value() {
  local -r secrets_bucket_name="$1"
  local -r source="$2"

  local -r key="${EC2_INSTANCE_REGION}/${source}"

  log_info "Downloading ${key}"

  aws s3 cp --quiet \
    "s3://${secrets_bucket_name}/${key}" /dev/stdout || exit 1
}

function assert_is_installed() {
  local -r name="$1"

  if [[ ! $(command -v ${name}) ]]; then
    log_error "The binary '$name' is required by this script but is not installed or in the system's PATH."
    exit 1
  fi
}

function address_type() {
  local -r ipv6="${1}"
  local type

  if [[ "$ipv6" == "true" ]]; then
    type="ipv6"
  else
    type="ipv4"
  fi

  echo "${type}"
}

function get_nomad_address() {
  local -r server="${1}"
  local -r ipv6="${2}"
  local -r interface="${3}"

  local type
  local variable_reference

  type="$(address_type "${ipv6}")"
  variable_reference="EC2_INSTANCE_${interface^^}_${type^^}_ADDRESS"

  echo "${!variable_reference}"
}

function get_vpc_cidr() {
  local -r ipv6="${1}"
  local -r interface="${2}"

  local type
  local variable_reference

  type="$(address_type "${ipv6}")"

  variable_reference="EC2_INSTANCE_${interface^^}_${type^^}_VPC_CIDR"

  echo "${!variable_reference}"
}

function get_instance_tags() {
  local -r instance_id="$1"
  local -r instance_region="${EC2_INSTANCE_REGION}"
  local tags=""
  local count_tags=""

  log_info "Looking up tags for Instance $instance_id in $instance_region"
  for ((i = 1; i <= "$MAX_RETRIES"; i++)); do
    tags=$(aws ec2 describe-tags \
      --region "$instance_region" \
      --filters "Name=resource-type,Values=instance" "Name=resource-id,Values=${instance_id}")
    count_tags=$(echo "$tags" | jq -r ".Tags? | length")
    if [[ "$count_tags" -gt 0 ]]; then
      log_info "This Instance $instance_id in $instance_region has Tags."
      echo "$tags"
      return
    else
      log_warn "This Instance $instance_id in $instance_region does not have any Tags."
      log_warn "Will sleep for $SLEEP_BETWEEN_RETRIES_SEC seconds and try again."
      sleep "$SLEEP_BETWEEN_RETRIES_SEC"
    fi
  done

  log_error "Could not find Instance Tags for $instance_id in $instance_region after $MAX_RETRIES retries."
  exit 1
}

function get_asg_size() {
  local -r asg_name="$1"
  local -r aws_region="${EC2_INSTANCE_REGION}"
  local asg_json=""

  log_info "Looking up the size of the Auto Scaling Group $asg_name in $aws_region"
  asg_json=$(aws autoscaling describe-auto-scaling-groups --region "$aws_region" --auto-scaling-group-names "$asg_name")
  echo "$asg_json" | jq -r '.AutoScalingGroups[0].DesiredCapacity'
}

function get_cluster_size() {
  local -r instance_tags="$1"
  local -r aws_region="${EC2_INSTANCE_REGION}"

  local asg_name=""
  asg_name=$(get_tag_value "$instance_tags" "$AWS_ASG_TAG_KEY")
  if [[ -z "$asg_name" ]]; then
    log_warn "This EC2 Instance does not appear to be part of an Auto Scaling Group, so cannot determine cluster size. Setting cluster size to 1."
    echo 1
  else
    get_asg_size "$asg_name"
  fi
}

# Get the value for a specific tag from the tags JSON returned by the AWS describe-tags:
# https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-tags.html
function get_tag_value() {
  local -r tags="$1"
  local -r tag_key="$2"

  echo "$tags" | jq -r ".Tags[] | select(.Key == \"$tag_key\") | .Value"
}

function generate_nomad_config() {
  umask 027

  local -r role="${1}"
  local -r server="${2}"
  local -r config_dir="${3}"
  local -r plugin_dir="${4}"
  local -r user="${5}"
  local -r gossip_encryption_key="${6}"
  local -r ca_file_path="${7}"
  local -r cert_file_path="${8}"
  local -r key_file_path="${9}"
  local -r consul_ca_file_path="${10}"
  local -r consul_cert_file_path="${11}"
  local -r consul_key_file_path="${12}"
  local -r consul_acl_token="${13}"
  local -r vault_ca_file_path="${14}"
  local -r vault_cert_file_path="${15}"
  local -r vault_key_file_path="${16}"
  local -r vault_token="${17}"
  local -r verify_server_hostname="${18}"
  local -r verify_https_client="${19}"
  local -r ipv6="${20}"
  local -r interface="${21}"

  local -r config_path="$config_dir/$NOMAD_CONFIG_FILE"

  local instance_id="${EC2_INSTANCE_ID}"
  local instance_region="${EC2_INSTANCE_REGION}"
  local instance_availability_zone="${EC2_INSTANCE_AVAILABILITY_ZONE}"
  local instance_type="${EC2_INSTANCE_TYPE}"

  local describe_instance
  describe_instance="$(aws ec2 describe-instances --output json --region "${instance_region}" --instance-id "${instance_id}" | jq -r ".Reservations[0].Instances[0]")"

  local instance_lifecycle
  instance_lifecycle="$(echo "${describe_instance}" | jq -r '.InstanceLifecycle | .required // "scheduled"')"

  local server_config=""

  local address

  address="$(get_nomad_address "${server}" "${ipv6}" "${interface}")"

  if [[ "$server" == "true" ]]; then
    local instance_tags=""
    local cluster_size=""

    instance_tags=$(get_instance_tags "$instance_id")
    cluster_size=$(get_cluster_size "$instance_tags")

    server_config=$(
      cat <<EOF
acl {
  enabled = true
}

server {
  enabled = true
  bootstrap_expect = $cluster_size
  encrypt = "$gossip_encryption_key"
  raft_multiplier = 1

  plan_rejection_tracker {
    enabled = true
    node_threshold = 100
    node_window = "3m"
  }

  default_scheduler_config {
    scheduler_algorithm             = "spread"
    memory_oversubscription_enabled = true
    reject_job_registration         = false

    preemption_config {
      system_scheduler_enabled   = true
      service_scheduler_enabled  = true
      batch_scheduler_enabled    = false
      sysbatch_scheduler_enabled = false
    }
  }
}
EOF
    )
  fi

  local client_config=""
  if [[ "$server" == "false" ]]; then
    client_config=$(
      cat <<EOF
client {
  enabled = true
  network_interface = "${interface}"
  node_class = "${instance_type}"
  options = {
    "fingerprint.network.disallow_link_local" = "true"
  }
  bridge_network_hairpin_mode = true

  meta {
    availability_zone = "${instance_availability_zone}"
    instance_id = "${instance_id}"
    instance_lifecycle = "${instance_lifecycle}"
    instance_type = "${instance_type}"
    role = "${role}"
  }
}

plugin "docker" {
  config {
    endpoint = "unix:///run/docker.sock"

    allow_privileged = true

    volumes {
      enabled      = true
      selinuxlabel = "z"
    }
  }
}

EOF
    )
  fi

  local vault_stanza=""

  if [[ "$server" == "true" ]]; then
    vault_stanza=$(
      cat <<EOF
  address          = "https://[::1]:8200"
  token            = "$vault_token"
  create_from_role = "nomad-cluster"
EOF
    )
  else
    vault_stanza=$(
      cat <<EOF
  address          = "https://vault.service.consul:8200"
EOF
    )
  fi

  log_info "Creating default Nomad config file in $config_path"

  cat >"$config_path" <<EOF
log_level          = "WARN"
plugin_dir         = "${plugin_dir}"
datacenter         = "$instance_availability_zone"
name               = "$instance_id"
region             = "$instance_region"

addresses {
  http = "127.0.0.1 ::1 ${address}"
  rpc  = "${address}"
  serf = "${address}"
}

advertise {
  http = "${address}"
  rpc  = "${address}"
  serf = "${address}"
}

$client_config

$server_config

tls {
  http = true
  rpc  = true

  ca_file   = "$ca_file_path"
  cert_file = "$cert_file_path"
  key_file  = "$key_file_path"

  verify_server_hostname = $verify_server_hostname
  verify_https_client    = $verify_https_client
}

telemetry {
  publish_allocation_metrics = true
  publish_node_metrics       = true
  disable_hostname           = true
  prometheus_metrics         = true
  collection_interval        = "1s"
}

consul {
  address      = "[::1]:8501"
  grpc_address = "[::1]:8502"

  ssl          = true
  verify_ssl   = true
  ca_file      = "$consul_ca_file_path"
  cert_file    = "$consul_cert_file_path"
  key_file     = "$consul_key_file_path"
  token        = "$consul_acl_token"
}

vault {
  enabled          = true
  ca_path          = "$vault_ca_file_path"
  cert_file        = "$vault_cert_file_path"
  key_file         = "$vault_key_file_path"
$vault_stanza
}
EOF
  chown "$user:$user" "$config_path"
}

function generate_ferm_config() {
  log_info "Writing ferm configuration"

  local server="$1"
  local ipv6="$2"
  local interface="$3"

  local template_path="/etc/ferm/ferm.d/1010-nomad.conf"

  local address
  local domain
  local vpc_cidr

  if [[ "$ipv6" == "true" ]]; then
    domain="ip6"
  else
    domain="ip"
  fi

  address="$(get_nomad_address "${server}" "${ipv6}" "${interface}")"
  vpc_cidr="$(get_vpc_cidr "${ipv6}" "${interface}")"

  local -r template=$(
    cat <<EOF
domain (ip ip6) table filter {
  chain OUTPUT {
    daddr (169.254.169.254 fd00:ec2::254) proto tcp mod owner uid-owner "nomad" ACCEPT;
  }
}

domain ({{ (ds "data").domain }}) table filter chain INPUT saddr {{ (ds "data").vpc_cidr }} daddr {{ (ds "data").address }} {
  # The port used for internal RPC communication between agents and
  # servers, and for inter-server traffic for the consensus algorithm
  # (raft).
  proto tcp dport 4647 ACCEPT;
}

{{ if conv.ToBool ((ds "data").server) }}
domain ({{ (ds "data").domain }}) table filter chain INPUT saddr {{ (ds "data").vpc_cidr }} daddr {{ (ds "data").address }} {
  # The port used for the gossip protocol for cluster membership. Both TCP
  # and UDP should be routable between the server nodes on this port.
  proto (tcp udp) dport 4648 ACCEPT;

  # The port used to run the HTTP server
  proto tcp dport 4646 ACCEPT;
}
{{ else }}
{{ end }}
EOF
  )

  echo "{ \"server\": ${server}, \"domain\": \"${domain}\", \"address\": \"${address}\", \"vpc_cidr\": \"${vpc_cidr}\" }" | jq '.' | gomplate \
    -i "${template}" -d data=stdin:///data.json >"${template_path}"

  chown root:root "${template_path}"
  chmod 600 "${template_path}"
}

function generate_systemd_config() {
  umask 022

  local -r nomad_bin_dir="${1}"
  local -r nomad_config_dir="${2}"
  local -r nomad_data_dir="${3}"
  local -r interface="${4}"
  local -r ipv6="${5}"
  local -r secrets_bucket_name="${6}"
  local -r server="${7}"
  local -r use_sudo="${8}"
  local nomad_user="${9}"

  shift 9

  local -r environment=("$@")
  local -r config_path="$nomad_config_dir/$NOMAD_CONFIG_FILE"

  if [[ "$use_sudo" == "true" ]]; then
    log_info "The --use-sudo flag is set, so running Nomad as the root user"
    nomad_user="root"
  fi

  log_info "Creating systemd config file to run Nomad in $SYSTEMD_CONFIG_PATH"

  local -r unit_config=$(
    cat <<EOF
[Unit]
Description="HashiCorp Nomad"
Documentation=https://www.nomadproject.io/
After=consul-online.target
After=docker.service
After=ferm.service
After=network-online.target
After=vault-online.target
Wants=consul-online.target
Wants=docker.service
Wants=ferm.service
Wants=network-online.target
Wants=vault-online.target
ConditionFileNotEmpty=$config_path

EOF
  )

  local -r service_config=$(
    cat <<EOF
[Service]
User=$nomad_user
Group=$nomad_user
ExecStart=$nomad_bin_dir/nomad agent -config $nomad_config_dir -data-dir $nomad_data_dir
ExecReload=/bin/kill --signal HUP \$MAINPID
KillMode=process
KillSignal=SIGINT
LimitNOFILE=65536
LimitNPROC=infinity
OOMScoreAdjust=-1000
Restart=on-failure
RestartSec=2
TasksMax=infinity

$(split_by_lines "Environment=" "${environment[@]}")

EOF
  )

  local -r install_config=$(
    cat <<EOF
[Install]
WantedBy=multi-user.target
EOF
  )

  echo -e "$unit_config" >"$SYSTEMD_CONFIG_PATH"
  echo -e "$service_config" >>"$SYSTEMD_CONFIG_PATH"
  echo -e "$install_config" >>"$SYSTEMD_CONFIG_PATH"

  if [[ "$server" == "true" ]]; then
    log_info "Creating systemd bootstrap config file ${NOMAD_BOOTSTRAP_SYSTEMD_CONFIG_PATH}"

    local address

    address="$(get_nomad_address "${server}" "${ipv6}" "${interface}")"

    local -r bootstrap_config=$(
      cat <<EOF
[Service]
Environment='SECRETS_BUCKET_NAME=${secrets_bucket_name}'
Environment='ADDRESS=${address}'

EOF
    )
    echo -e "$bootstrap_config" >"${NOMAD_BOOTSTRAP_SYSTEMD_CONFIG_PATH}"
  fi
}

function start_nomad() {
  log_info "Reloading systemd config and starting Nomad"

  sudo systemctl daemon-reload
  sudo systemctl enable nomad-online.target
  sudo systemctl --no-block restart ferm.service nomad-online.target
}

# Based on: http://unix.stackexchange.com/a/7732/215969
function get_owner_of_path() {
  local -r path="$1"
  ls -ld "$path" | awk '{print $3}'
}

function trust-ca() {
  local -r source="${1}"
  local name

  name="$(basename "${source}")"

  local -r path="/etc/pki/ca-trust/source/anchors/${name}"

  cp -f "${source}" "${path}"
  chown root:root "${path}"
  chmod 644 "${path}"

  update-ca-trust
}

function run() {
  if [[ ! -f "/etc/sysconfig/ec2-environment" ]]; then
    print_usage

    log_error "/etc/sysconfig/ec2-environment: No such file"

    exit 1
  fi

  set -o allexport
  source "/etc/sysconfig/ec2-environment"
  set +o allexport

  local role=""
  local server="false"
  local environment=()

  local secrets_bucket_name=""
  local verify_server_hostname="false"
  local verify_https_client="false"

  local ipv6="false"
  local interface="eth0"

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
    --role)
      assert_not_empty "$key" "$2"
      role="$2"
      shift
      ;;
    --secrets-bucket-name)
      assert_not_empty "$key" "$2"
      secrets_bucket_name="$2"
      shift
      ;;
    --verify-server-hostname)
      verify_server_hostname="true"
      ;;
    --verify-https-client)
      verify_https_client="true"
      ;;
    --environment)
      assert_not_empty "$key" "$2"
      environment+=("$2")
      shift
      ;;
    --ipv6)
      ipv6="true"
      ;;
    --interface)
      assert_not_empty "$key" "$2"
      interface="$2"
      shift
      ;;
    --help)
      print_usage
      exit
      ;;
    *)
      log_error "Unrecognized argument: $key"
      print_usage
      exit 1
      ;;
    esac

    shift
  done

  assert_not_empty "--role" "$role"
  assert_not_empty "--secrets-bucket-name" "$secrets_bucket_name"

  if [[ "$role" == "server" ]]; then
    server="true"
  elif [[ "$role" == "client" ]]; then
    server="false"
  elif [[ "$role" == "bastion" ]]; then
    server="false"
  else
    log_error "Unrecognized value for the --role flag."
    exit 1
  fi

  local use_sudo

  if [[ "$server" == "false" ]]; then
    use_sudo="true"
  else
    use_sudo="false"
  fi

  assert_is_installed "systemctl"
  assert_is_installed "aws"
  assert_is_installed "curl"
  assert_is_installed "jq"
  assert_is_installed "gomplate"

  local config_dir
  local plugin_dir
  local data_dir
  local bin_dir
  local user

  config_dir=$(cd "$SCRIPT_DIR/../config" && pwd)
  plugin_dir=$(cd "$SCRIPT_DIR/../plugins" && pwd)
  data_dir=$(cd "$SCRIPT_DIR/../data" && pwd)
  bin_dir=$(cd "$SCRIPT_DIR/../bin" && pwd)
  user=$(get_owner_of_path "$config_dir")

  local nomad_ca_file_path=""
  local nomad_cert_file_path=""
  local nomad_key_file_path=""

  local consul_ca_file_path=""
  local consul_cert_file_path=""
  local consul_key_file_path=""

  local vault_ca_file_path=""
  local vault_cert_file_path=""
  local vault_key_file_path=""
  local vault_token=""

  local type

  if [[ "$server" == "true" ]]; then
    type="server"
  else
    type="client"
  fi

  local gossip_encryption_key=""

  if [[ "$role" == "server" ]]; then
    gossip_encryption_key="$(get_object_value "${secrets_bucket_name}" "${role}/nomad/nomad-gossip-encryption-key")"
  fi

  local consul_acl_token=""
  consul_acl_token="$(get_object_value "${secrets_bucket_name}" "${role}/nomad/consul-acl-token-nomad-${type}")"

  local vault_token=""

  if [[ "$role" == "server" ]]; then
    vault_token="$(get_object_value "${secrets_bucket_name}" "${role}/nomad/vault-token-nomad-server")"
  fi

  local tls_path
  local tls_ca_path

  tls_path="$(cd "$SCRIPT_DIR/../tls" && pwd)"
  tls_ca_path="$(cd "$SCRIPT_DIR/../tls/ca" && pwd)"

  nomad_ca_file_path="${tls_ca_path}/nomad-ca.pem"
  nomad_cert_file_path="${tls_path}/nomad-${type}.pem"
  nomad_key_file_path="${tls_path}/nomad-${type}-key.pem"

  get_object "${secrets_bucket_name}" \
    "${role}/nomad/nomad-ca.pem" \
    "${nomad_ca_file_path}" \
    "${user}"

  get_object "${secrets_bucket_name}" \
    "${role}/nomad/nomad-${type}.pem" \
    "${nomad_cert_file_path}" \
    "${user}"

  get_object "${secrets_bucket_name}" \
    "${role}/nomad/nomad-${type}-key.pem" \
    "${nomad_key_file_path}" \
    "${user}"

  # Consul TLS
  consul_ca_file_path="${tls_ca_path}/consul-ca.pem"
  consul_cert_file_path="${tls_path}/consul-nomad.pem"
  consul_key_file_path="${tls_path}/consul-nomad-key.pem"

  get_object "${secrets_bucket_name}" \
    "${role}/nomad/consul-ca.pem" \
    "${consul_ca_file_path}" \
    "${user}"

  get_object "${secrets_bucket_name}" \
    "${role}/nomad/consul-nomad.pem" \
    "${consul_cert_file_path}" \
    "${user}"

  get_object "${secrets_bucket_name}" \
    "${role}/nomad/consul-nomad-key.pem" \
    "${consul_key_file_path}" \
    "${user}"

  # Vault TLS
  vault_ca_file_path="${tls_ca_path}/vault-ca.pem"
  vault_cert_file_path="${tls_path}/vault-nomad.pem"
  vault_key_file_path="${tls_path}/vault-nomad-key.pem"

  get_object "${secrets_bucket_name}" \
    "${role}/nomad/vault-ca.pem" \
    "${vault_ca_file_path}" \
    "${user}"

  get_object "${secrets_bucket_name}" \
    "${role}/nomad/vault-nomad.pem" \
    "${vault_cert_file_path}" \
    "${user}"

  get_object "${secrets_bucket_name}" \
    "${role}/nomad/vault-nomad-key.pem" \
    "${vault_key_file_path}" \
    "${user}"

  generate_nomad_config \
    "$role" \
    "$server" \
    "$config_dir" \
    "$plugin_dir" \
    "$user" \
    "$gossip_encryption_key" \
    "$nomad_ca_file_path" \
    "$nomad_cert_file_path" \
    "$nomad_key_file_path" \
    "$consul_ca_file_path" \
    "$consul_cert_file_path" \
    "$consul_key_file_path" \
    "$consul_acl_token" \
    "$vault_ca_file_path" \
    "$vault_cert_file_path" \
    "$vault_key_file_path" \
    "$vault_token" \
    "$verify_server_hostname" \
    "$verify_https_client" \
    "$ipv6" \
    "$interface"

  generate_systemd_config \
    "$bin_dir" \
    "$config_dir" \
    "$data_dir" \
    "$interface" \
    "$ipv6" \
    "$secrets_bucket_name" \
    "$server" \
    "$use_sudo" \
    "$user" \
    "${environment[@]}"

  generate_ferm_config \
    "$server" \
    "$ipv6" \
    "$interface"

  trust-ca "$nomad_ca_file_path"

  cat >"/etc/profile.d/nomad.sh" <<EOF
export NOMAD_ADDR=https://[::1]:4646
EOF

  chown "root:root" "/etc/profile.d/nomad.sh"
  chmod 644 "/etc/profile.d/nomad.sh"

  start_nomad
}

run "$@"
